### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by caseyjlaw** [devanshkv/fetch#1]
I'm having a bit of trouble getting tensorflow installed correctly. One thing that would help is to be explicit that the conda-forge channel does not work. That is my default.
Also, my understanding is that the cuda compiler version (`nvcc --version`) must be aligned with cudatool version.

**Comment by caseyjlaw** [comment]
Also, I'm getting a warning about a python module "mkl" used by theano. Probably should advise this:
`conda install mkl-service`

**Comment by devanshkv** [comment]
@caseyjlaw yes the cudatoolkit version and the local cuda installation version has to match, thanks for bringing this up, I'll soon add these to the installation instructions.
Since we are not using the theano backend, we never got the mkl warning. With the recent upgrades to tensorflow, numpy and scikit-image, there are a lot more warnings popping up, I am working on a newer version but won't be able to push that before the end of the month.
